package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.VerticalScrollArrangement;
class Screen6 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Image Image2;
  private Label Label1;
  private Image Image1;
  private TableArrangement TableArrangement1;
  private Label Label2;
  private VerticalScrollArrangement VerticalScrollArrangement1;
  private Label Label3;
  private Image Image3;
  private Label Label4;
  private Label Label5;
  private Image Image4;
  private Label Label6;
  private Label Label7;
  private Image Image5;
  private Label Label8;
  private Label Label9;
  private Image Image6;
  private Label Label10;
  private Label Label11;
  private Label Label12;
  private Image Image7;
  private Label Label13;
  private Label Label14;
  private Image Image8;
  private Label Label15;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Scrollable(true);
    this.Title("Screen6");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Height(-1015);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Image2 = new Image(HorizontalArrangement1);
    Image2.Height(-1014);
    Image2.Width(-1020);
    Image2.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA\n POMOC");
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(-1014);
    Image1.Width(-1020);
    Image1.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Height(-1010);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    Label2 = new Label(TableArrangement1);
    Label2.Column(0);
    Label2.FontBold(true);
    Label2.FontSize(22);
    Label2.Height(-1010);
    Label2.Width(LENGTH_FILL_PARENT);
    Label2.Row(0);
    Label2.Text("NAGŁE ZATRZYMANIE KRĄŻENIA");
    VerticalScrollArrangement1 = new VerticalScrollArrangement(this);
    Label3 = new Label(VerticalScrollArrangement1);
    Label3.Height(790);
    Label3.Width(310);
    Label3.Text("Nagłe zatrzymanie krążenia (NZK) definiuje się jako ustanie ruchu krwi w łożysku naczyniowym. Następnie występuje wtórne zatrzymanie oddechu, co  powoduje później nieodwracalne uszkodzenie mózgu. Gdy mamy do czynienia z NZK musimy postępować zgodnie z algorytmem Basic Life Support (BLS). Czynności polegają na prawidłowym zapewnieniu drożności dróg oddechowych, wspomaganiu oddychania oraz krążenia. Do tego nie jest nam potrzebny sprzęt medyczny, jednak środki ochrony (np. maseczka do sztucznego oddychania, rękawiczki) są wskazane, aby zabezpieczyć swoje zdrowie oraz życie. Aby udrożnić drogi oddechowe należy wykonać manewr czoło-żuchwa odginając głowę do tyłu. Aby wspomagać oddech wdmuchujemy powietrze z własnych płuc metodą usta- usta. Natomiast do podtrzymania krążenia wykonuje się uciski klatki piersiowej.\n\n Gdy jesteśmy już po wstępnej ocenie stanu poszkodowanego i wezwaliśmy pomoc należy przystąpić do resuscytacji krążeniowo-  oddechowej (RKO)- czyli zespół czynności stosowanych u poszkodowanego, u którego wystąpiło podejrzenie nagłego zatrzymania krążenia, czyli ustanie czynności serca z utratą świadomości i bezdechem. Celem resuscytacji jest utrzymanie przepływu krwi przez mózg i mięsień sercowy oraz przywrócenie czynności własnej układu krążenia. \nKolejnym krokiem w algorytmie są uciśnięcia klatki piersiowej na zmianę z wykonywanie sztucznego oddychania. Na samym początku należy wysłać świadka zdarzenia po AED i przystąpić niezwłocznie do pośredniego masażu serca. Osobę poszkodowaną należy ułożyć na plecach na twardym podłożu. Klęknąć w lekkim rozkroku przy poszkodowanym. Następnie odsłonić klatkę piersiową, nachylić się i ułożyć splecione ręce na środku klatki piersiowej. Należy uciskać nasadą nadgarstka, więc palce trzeba oderwać od ciała, aby nie uciskać żeber. Uciskanie klatki piersiowej u osoby dorosłej powinno być wykonane na głębokość 5-6cm. Częstość uciśnięć u osoby dorosłej wynosi 100-120/minutę. ");
    Image3 = new Image(VerticalScrollArrangement1);
    Image3.Height(180);
    Image3.Width(320);
    Image3.Picture("ukp.png");
    Label4 = new Label(VerticalScrollArrangement1);
    Label4.FontBold(true);
    Label4.Width(310);
    Label4.Text("Miejsce Uciskania Klatki Piersiowej");
    Label5 = new Label(VerticalScrollArrangement1);
    Label5.Height(200);
    Label5.Width(310);
    Label5.Text("\nPo wykonaniu 30 uciśnięć klatki piersiowej wykonujemy 2 wdechy ratownicze techniką usta-usta Wdech powinien trwać około 1sekunde do wyraźnego uniesienia się klatki piersiowej. Należy udrożnić drogi oddechowe, zatkać nos poszkodowanego, objąć szczelnie usta poszkodowanego i następnie wdmuchać powietrze, obserwując przy tym ruch klatki piersiowej. Po wykonaniu 2 wdechów ponownie przystępujemy do masażu serca. Aż do momentu przyniesienia defibrylatora AED. ");
    Image4 = new Image(VerticalScrollArrangement1);
    Image4.Height(150);
    Image4.Width(320);
    Image4.Picture("defibrylator.png");
    Label6 = new Label(VerticalScrollArrangement1);
    Label6.FontBold(true);
    Label6.Height(32);
    Label6.Width(310);
    Label6.Text("Automatyczny zewnętrzny defibrylator i symbol jego umieszczania");
    Label7 = new Label(VerticalScrollArrangement1);
    Label7.Height(430);
    Label7.Width(310);
    Label7.Text("\nPo podłączeniu defibrylatora AED należy postępować według wydawanych przez niego poleceń."+
    "RKO należy prowadzić do momentu przybycia i przejęcia czynności ratowniczych przez wykwalifikowany zespół medyczny. Przerwać można jedynie w przypadku, gdy osoba odzyska oddech, świadomość i zacznie się ruszać jak również w momencie gdy osoba ratująca jest zmęczona , opada z sił, a także gdy otoczenie zmieni się na zagrażające życiu.\n\n Jeśli chodzi o RKO u dzieci algorytm wygląda podobnie jak u dorosłych. Jest tylko jedna kluczowa zmiana u dzieci resuscytacje rozpoczynamy od wykonania 5 oddechów ratowniczych, gdyż dzieci zatrzymują się głównie z przyczyn oddechowych. Różnica jest również w technice wykonywania RKO, a mianowicie u dzieci uciskanie klatki piersiowej wykonujemy jedną ręką na głębokość ok 5cm. Częstość uciśnięć jest taka sama jak u dorosłych 100-120/minutę. Stosunek pozostaje bez zmian 30 uciśnięć klatki piersiowej i 2 wdechy ratownicze.");
    Image5 = new Image(VerticalScrollArrangement1);
    Image5.Height(160);
    Image5.Width(320);
    Image5.Picture("rkodziecko.png");
    Label8 = new Label(VerticalScrollArrangement1);
    Label8.FontBold(true);
    Label8.Height(17);
    Label8.Width(310);
    Label8.Text("RKO Dziecka");
    Label9 = new Label(VerticalScrollArrangement1);
    Label9.Height(200);
    Label9.Width(310);
    Label9.Text("\nJeśli chodzi o RKO u noworodków algorytm wygląda identycznie jak u dzieci. Resuscytacje rozpoczynamy od wykonania 5 oddechów ratowniczych, gdyż noworodku zatrzymują się głównie z przyczyn oddechowych. U niemowląt uciskanie klatki piersiowej wykonujemy dwoma palcami na głębokość ok 4cm. Częstość uciśnięć jest taka sama jak u dorosłych czy dzieci 100-120/minutę. Stosunek pozostaje bez zmian 30 uciśnięć klatki piersiowej i 2 wdechy ratownicze.");
    Image6 = new Image(VerticalScrollArrangement1);
    Image6.Height(185);
    Image6.Width(320);
    Image6.Picture("pierwsza_pomoc_noworodek.jpg");
    Label10 = new Label(VerticalScrollArrangement1);
    Label10.FontBold(true);
    Label10.Height(17);
    Label10.Width(310);
    Label10.Text("RKO Niemowlę");
    Label11 = new Label(VerticalScrollArrangement1);
    Label11.Height(210);
    Label11.Width(310);
    Label11.Text("\nKolejnym przypadkiem minimalnych zmian w RKO jest kobieta w zaawansowanej ciąży. Jeśli dojdzie do zatrzymania krążenia należy położyć kobietę ciężarną na lewym boku, dlatego aby macica nie uciskała na aortę i żyłę główną dolną, bo ucisk na te naczynia może doprowadzić do zmniejszenia rzutu serca, ponieważ krew nie wraca w odpowiedniej ilości do serca. Powikłaniem może być odklejenie łożyska. Dlatego ważnie jest, aby pamiętać, żeby prawy bok był lekko uniesiony, gdyż w ten sposób zapewniamy bezpieczeństwo matce i dziecku. ");
    Label12 = new Label(VerticalScrollArrangement1);
    Label12.Height(160);
    Label12.Width(310);
    Label12.Text("Gdy mamy do czynienia z niedrożnością dróg oddechowych, która jest spowodowana ciałem obcym to tak zwane zadławienie. Efektem może być utrata przytomności, zatrzymanie oddechu i krążenia a nawet śmierć. Zadławienie częściej występuje u dzieci niż u osób dorosłych. Niedrożność dróg oddechowych możemy podzielić na całkowitą i częściową.");
    Image7 = new Image(VerticalScrollArrangement1);
    Image7.Height(150);
    Image7.Width(320);
    Image7.Picture("zadlawienie.png");
    Label13 = new Label(VerticalScrollArrangement1);
    Label13.FontBold(true);
    Label13.Height(17);
    Label13.Width(310);
    Label13.Text("Rodzaje Niedrożność Dróg Oddechowych");
    Label14 = new Label(VerticalScrollArrangement1);
    Label14.Height(300);
    Label14.Width(310);
    Label14.Text("\n Postępowanie ratownicze przy częściowej niedrożności dróg oddechowych polega na zachęcaniu osoby poszkodowanej do kaszlu oraz obserwacja jej stanu. Natomiast postępowanie ratownicze podczas całkowitej niedrożności dróg oddechowych należy wykonać 5 uderzeń w okolice międzyłopatkową jeśli będą nie skuteczne należy wykonać 5 uciśnięć nadbrzusza (rycina 2.6.) i tak na zmianę do momentu wypadnięcia ciała obcego. Natomiast gdy osoba poszkodowana straci przytomność należy niezwłocznie przystąpić do RKO rozpoczynając od 30 uciśnięć klatki piersiowej następnie wykonanie 2 wdechów ratowniczych po uprzednim sprawdzeniu jamy ustnej czy nie znajduje się w niej widoczne ciało obce, które można bez problemu usunąć.");
    Image8 = new Image(VerticalScrollArrangement1);
    Image8.Height(140);
    Image8.Width(310);
    Image8.Picture("zadlawieniepostepowanie.png");
    Label15 = new Label(VerticalScrollArrangement1);
    Label15.FontBold(true);
    Label15.Height(17);
    Label15.Width(310);
    Label15.Text("Postępowanie przy zadławieniu");
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}