package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.PhoneCall;
class Screen11 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Image Image3;
  private Label Label1;
  private Image Image1;
  private TableArrangement TableArrangement1;
  private Image Image2;
  private Button Button2;
  private Button Button3;
  private Button Button4;
  private Button Button5;
  private PhoneCall PhoneCall1;
  private PhoneCall PhoneCall2;
  private PhoneCall PhoneCall3;
  private PhoneCall PhoneCall4;
  private PhoneCall PhoneCall5;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Title("Screen11");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Height(-1014);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Image3 = new Image(HorizontalArrangement1);
    Image3.Height(-1014);
    Image3.Width(-1020);
    Image3.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA\n POMOC");
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(-1014);
    Image1.Width(-1020);
    Image1.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Columns(1);
    TableArrangement1.Height(-1075);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(5);
    Image2 = new Image(TableArrangement1);
    Image2.Column(0);
    Image2.Height(-1035);
    Image2.Width(-1098);
    Image2.Picture("112.jpg");
    Image2.Row(0);
    Button2 = new Button(TableArrangement1);
    Button2.Column(0);
    Button2.FontBold(true);
    Button2.FontSize(20);
    Button2.Row(1);
    Button2.Text("NUMER ALARMOWY - 112");
    Button3 = new Button(TableArrangement1);
    Button3.Column(0);
    Button3.FontBold(true);
    Button3.FontSize(20);
    Button3.Row(2);
    Button3.Text("POLICJA - 997");
    Button4 = new Button(TableArrangement1);
    Button4.Column(0);
    Button4.FontBold(true);
    Button4.FontSize(20);
    Button4.Row(3);
    Button4.Text("STRAŻ POŻARNA - 998");
    Button5 = new Button(TableArrangement1);
    Button5.Column(0);
    Button5.FontBold(true);
    Button5.FontSize(20);
    Button5.Row(4);
    Button5.Text("POGOROWIE RATUNKOWE - 999");
    PhoneCall1 = new PhoneCall(this);
    PhoneCall1.PhoneNumber("112");
    PhoneCall2 = new PhoneCall(this);
    PhoneCall2.PhoneNumber("112");
    PhoneCall3 = new PhoneCall(this);
    PhoneCall3.PhoneNumber("997");
    PhoneCall4 = new PhoneCall(this);
    PhoneCall4.PhoneNumber("998");
    PhoneCall5 = new PhoneCall(this);
    PhoneCall5.PhoneNumber("999");
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}