package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
class Screen28 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Image Image1;
  private Label Label1;
  private Image Image2;
  private TableArrangement TableArrangement1;
  private Label Label2;
  private Label Label3;
  private Label Label4;
  private Label Label5;
  private Label Label6;
  private Image Image3;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Title("Screen28");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Height(-1014);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(-1014);
    Image1.Width(-1020);
    Image1.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA\n POMOC");
    Image2 = new Image(HorizontalArrangement1);
    Image2.Height(-1014);
    Image2.Width(-1020);
    Image2.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Columns(1);
    TableArrangement1.Height(-1050);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(6);
    Label2 = new Label(TableArrangement1);
    Label2.Column(0);
    Label2.FontBold(true);
    Label2.FontSize(20);
    Label2.Row(0);
    Label2.Text("KONTAKT:");
    Label3 = new Label(TableArrangement1);
    Label3.Column(0);
    Label3.Width(LENGTH_FILL_PARENT);
    Label3.Row(1);
    Label3.Text("Kinga Kunefał oraz Joanna Żurawik");
    Label4 = new Label(TableArrangement1);
    Label4.Column(0);
    Label4.Row(2);
    Label4.Text("66-001 Zielona Góra");
    Label5 = new Label(TableArrangement1);
    Label5.Column(0);
    Label5.Row(4);
    Label5.Text("KK&JZ@gmail.com");
    Label6 = new Label(TableArrangement1);
    Label6.Column(0);
    Label6.Row(3);
    Label6.Text("ul. Strumykowa 1");
    Image3 = new Image(TableArrangement1);
    Image3.Column(0);
    Image3.Width(LENGTH_FILL_PARENT);
    Image3.Picture("LOGOFIRMY2.jpg");
    Image3.Row(5);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}