package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.VerticalScrollArrangement;
import com.google.appinventor.components.runtime.Button;
class Screen_test1 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement4;
  private Image Image11;
  private Label Label1;
  private Image Image10;
  private TableArrangement TableArrangement1;
  private Label Label3;
  private VerticalScrollArrangement VerticalScrollArrangement1;
  private Label Label5;
  private Button Button1;
  private Button Button2;
  private Button Button3;
  private Button Button4;
  private Label Label6;
  private Button Button5;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Title("Screen_test1");
    HorizontalArrangement4 = new HorizontalArrangement(this);
    HorizontalArrangement4.Height(-1015);
    HorizontalArrangement4.Width(LENGTH_FILL_PARENT);
    Image11 = new Image(HorizontalArrangement4);
    Image11.Height(-1014);
    Image11.Width(-1020);
    Image11.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement4);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA \n POMOC");
    Image10 = new Image(HorizontalArrangement4);
    Image10.Height(-1014);
    Image10.Width(-1020);
    Image10.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Columns(1);
    TableArrangement1.Height(-1005);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    Label3 = new Label(TableArrangement1);
    Label3.Column(0);
    Label3.FontBold(true);
    Label3.FontSize(20);
    Label3.Height(-1008);
    Label3.Width(-1098);
    Label3.Row(0);
    Label3.Text("TEST ");
    VerticalScrollArrangement1 = new VerticalScrollArrangement(this);
    VerticalScrollArrangement1.Height(700);
    VerticalScrollArrangement1.Width(LENGTH_FILL_PARENT);
    Label5 = new Label(VerticalScrollArrangement1);
    Label5.FontSize(14);
    Label5.Height(-1010);
    Label5.Width(LENGTH_FILL_PARENT);
    Label5.Text("1. Od jakiej czynności rozpoczniesz udzielanie pierwszej pomocy?");
    Button1 = new Button(VerticalScrollArrangement1);
    Button1.Width(LENGTH_FILL_PARENT);
    Button1.Text("a. uciskania klatki piersiowej");
    Button2 = new Button(VerticalScrollArrangement1);
    Button2.Width(LENGTH_FILL_PARENT);
    Button2.Text("b. sprawdzenia oddechu");
    Button3 = new Button(VerticalScrollArrangement1);
    Button3.Width(LENGTH_FILL_PARENT);
    Button3.Text("c. sprawdzenia przytomności");
    Button4 = new Button(VerticalScrollArrangement1);
    Button4.Width(LENGTH_FILL_PARENT);
    Button4.Text("d. oceny bezpieczeństwa miejsca zdarzenia");
    Label6 = new Label(VerticalScrollArrangement1);
    Label6.Width(LENGTH_FILL_PARENT);
    Label6.Text("Wybierz jedną odpowiedź");
    Button5 = new Button(VerticalScrollArrangement1);
    Button5.Text("Dalej");
    Button5.Visible(false);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}