package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Button;
class Screen10 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Image Image2;
  private Label Label1;
  private Image Image1;
  private TableArrangement TableArrangement1;
  private Button Button3;
  private Button Button4;
  private Button Button5;
  private Button Button6;
  private Button Button7;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Title("Screen10");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Height(-1015);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Image2 = new Image(HorizontalArrangement1);
    Image2.Height(-1014);
    Image2.Width(-1020);
    Image2.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA\n POMOC");
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(-1014);
    Image1.Width(-1020);
    Image1.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Columns(1);
    TableArrangement1.Height(-1050);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(5);
    Button3 = new Button(TableArrangement1);
    Button3.Column(0);
    Button3.Row(0);
    Button3.Text("RKO Dorosłego");
    Button4 = new Button(TableArrangement1);
    Button4.Column(0);
    Button4.Row(1);
    Button4.Text("RKO Dziecka");
    Button5 = new Button(TableArrangement1);
    Button5.Column(0);
    Button5.Row(2);
    Button5.Text("RKO Niemowlę");
    Button6 = new Button(TableArrangement1);
    Button6.Column(0);
    Button6.Row(3);
    Button6.Text("RKO Dorosłego z AED");
    Button7 = new Button(TableArrangement1);
    Button7.Column(0);
    Button7.Width(-1098);
    Button7.Row(4);
    Button7.Text("Zadławienie");
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}