package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Button;
class Screen2 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Image Image2;
  private Label Label1;
  private Image Image1;
  private TableArrangement TableArrangement1;
  private Button Button1;
  private Button Button2;
  private Button Button3;
  private Button Button4;
  private Button Button5;
  private Button Button6;
  protected void $define() {
    this.AppName("PierwszaPomoc");
    this.Title("Screen2");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Height(-1015);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Image2 = new Image(HorizontalArrangement1);
    Image2.Height(-1014);
    Image2.Width(-1020);
    Image2.Picture("unnamed.png");
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontSize(27);
    Label1.Height(-1014);
    Label1.Width(LENGTH_FILL_PARENT);
    Label1.Text("PIERWSZA\n POMOC");
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(-1014);
    Image1.Width(-1020);
    Image1.Picture("logo2.png");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Height(LENGTH_FILL_PARENT);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(6);
    Button1 = new Button(TableArrangement1);
    Button1.Column(0);
    Button1.Width(-1098);
    Button1.Row(0);
    Button1.Text("Ocena Miejsca Zdarzenia");
    Button2 = new Button(TableArrangement1);
    Button2.Column(0);
    Button2.Row(1);
    Button2.Text("Wstępna Ocena Poszkodowanego");
    Button3 = new Button(TableArrangement1);
    Button3.Column(0);
    Button3.Row(2);
    Button3.Text("Nagłe Zatrzymanie Krążenia");
    Button4 = new Button(TableArrangement1);
    Button4.Column(0);
    Button4.Row(3);
    Button4.Text("Rany");
    Button5 = new Button(TableArrangement1);
    Button5.Column(0);
    Button5.Row(4);
    Button5.Text("Urazy");
    Button6 = new Button(TableArrangement1);
    Button6.Column(0);
    Button6.Row(5);
    Button6.Text("Stany Nagłe");
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}